spring:
  application:
    name: erueka-server
server:
  port: 1111
eureka:
  server:
#  关闭自我保护机制
    enable-self-preservation: false  
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/      
