spring:
  application:
    name: erueka-server
server:
  port: 1112
eureka:
  server:
#  关闭自我保护机制
    enable-self-preservation: false  
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
    healthcheck:
      enable: true  